version: '2'

services:
  postgres:
    restart: always
    image: postgres:latest
    ports:
    - "5438:5432"
    networks:
    - adbuy_network
    volumes:
    - ./volumes/postgres/data:/var/lib/postgresql/data:Z
    - ./volumes/postgres/conf/postgresql.conf:/etc/postgresql/postgresql.conf:Z
    environment:
    - POSTGRES_PASSWORD=build_password
    - PGPASSWORD=build_password


networks:
  adbuy_network:
    driver: bridge