# Generated by Django 2.1.7 on 2019-03-28 19:36

import datetime
import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdTimetable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateField(db_index=True, verbose_name='Начало показа')),
                ('weekdays', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(blank=True, choices=[('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thr', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')], default=(('mon', 'Понедельник'), ('tue', 'Вторник'), ('wed', 'Среда'), ('thr', 'Четверг'), ('fri', 'Пятница'), ('sat', 'Суббота'), ('sun', 'Воскресенье')), max_length=3, verbose_name='Дни недели'), size=None)),
                ('day_count', models.IntegerField(verbose_name='Дней показа')),
                ('cpm', models.IntegerField(verbose_name='CPM (руб. за 1000 показов)')),
                ('time_create', models.DateTimeField(default=datetime.datetime(2019, 3, 28, 19, 36, 15, 856496), verbose_name='Время создания')),
                ('time_update', models.DateTimeField(default=datetime.datetime(2019, 3, 28, 19, 36, 15, 856527), verbose_name='Время изменения')),
            ],
        ),
        migrations.AlterModelOptions(
            name='ad',
            options={'verbose_name': 'Объявление', 'verbose_name_plural': 'Объявления'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.AlterField(
            model_name='ad',
            name='categories',
            field=models.ManyToManyField(related_name='ads', to='ad_app.Category', verbose_name='Категории'),
        ),
        migrations.AddField(
            model_name='adtimetable',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ad_app.Ad', verbose_name='Объявление'),
        ),
        migrations.AddField(
            model_name='adtimetable',
            name='categories',
            field=models.ManyToManyField(related_name='ad_timetables', to='ad_app.Category', verbose_name='Категории'),
        ),
    ]
