# Generated by Django 2.1.7 on 2019-03-29 11:08

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0002_auto_20190328_1936'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdCalendarDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(db_index=True, verbose_name='Дата')),
                ('cpm', models.IntegerField(db_index=True, verbose_name='CPM (руб. за 1000 показов)')),
                ('ad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_dates', to='ad_app.Ad', verbose_name='Объявление')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calendar_dates', to='ad_app.Category', verbose_name='Категория')),
            ],
        ),
        migrations.AlterModelOptions(
            name='adtimetable',
            options={'verbose_name': 'Расписание показов', 'verbose_name_plural': 'Расписания показов'},
        ),
        migrations.AlterField(
            model_name='adtimetable',
            name='ad',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='ad_app.Ad', verbose_name='Объявление'),
        ),
        migrations.AlterField(
            model_name='adtimetable',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 11, 8, 49, 240002), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='adtimetable',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 11, 8, 49, 240026), verbose_name='Время изменения'),
        ),
        migrations.AddField(
            model_name='adcalendardate',
            name='timetable',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timetables', to='ad_app.AdTimetable', verbose_name='Расписание'),
        ),
    ]
