# Generated by Django 2.1.7 on 2019-03-29 12:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0003_auto_20190329_1108'),
    ]

    operations = [
        migrations.CreateModel(
            name='StatDailyView',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('daily_views', models.IntegerField(verbose_name='Просмотров в день')),
            ],
            options={
                'verbose_name': 'Статистика показов',
                'verbose_name_plural': 'Статистики показов',
            },
        ),
        migrations.AlterModelOptions(
            name='adcalendardate',
            options={'verbose_name': 'День показа', 'verbose_name_plural': 'Дни показа'},
        ),
        migrations.AlterField(
            model_name='adtimetable',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 12, 6, 55, 831476), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='adtimetable',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 12, 6, 55, 831501), verbose_name='Время изменения'),
        ),
    ]
