# Generated by Django 2.1.7 on 2019-03-29 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ad_app', '0004_auto_20190329_1206'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StatDailyView',
        ),
        migrations.AddField(
            model_name='category',
            name='stat_views_daily',
            field=models.IntegerField(default=0, verbose_name='Просимотров в день'),
        ),
        migrations.AlterField(
            model_name='adtimetable',
            name='time_create',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 18, 42, 9, 556388), verbose_name='Время создания'),
        ),
        migrations.AlterField(
            model_name='adtimetable',
            name='time_update',
            field=models.DateTimeField(default=datetime.datetime(2019, 3, 29, 18, 42, 9, 556421), verbose_name='Время изменения'),
        ),
    ]
